version: "3.8"
x-logging: &default-logging
  options:
    max-size: '10m'
    max-file: '1'
  driver: json-file
services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_TAG-latest}
    container_name: portainer
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/volumes/portainer:/data
    logging: *default-logging
  mysql:
    image: mysql:${MYSQL_TAG-latest}
    container_name: mysql
    command: mysqld --sql_mode='NO_ENGINE_SUBSTITUTION'
    restart: on-failure
    ports:
        - 3306:3306
    env_file:
      - .mysql.env
    volumes:
      - /var/volumes/mysql:/var/lib/mysql
    logging: *default-logging
  cloud-beaver: #MySQL client
    image: dbeaver/cloudbeaver:${CLOUD_BEAVER_TAG-latest}
    container_name: cloud-beaver
    restart: on-failure
    ports:
        - 3360:8978
    volumes:
      - /var/volumes/cloudbeaver:/opt/cloudbeaver/workspace
    links:
      - mysql      
    logging: *default-logging        
  mongo:
    image: mongo:${MONGO_TAG-latest}
    container_name: mongo
    command: sh -c "mongod --bind_ip_all --profile 1 --slowms 60000 --slowOpSampleRate 1.0"
    restart: on-failure
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017     
    volumes:
      - /var/volumes/mongodb:/data/db
    logging: *default-logging
  mongo-express: #Mongo Client
    image: mongo-express:${MONGO_EXPRESS_TAG-latest}
    ports:
      - 8081:8081
    env_file:
      - .mongo-express.env
    links:
      - mongo 
  redis:
    image: redis:${REDIS_TAG-latest}
    container_name: redis
    restart: on-failure
    volumes:
      - /var/volumes/redis:/data
    ports:
      - 6379:6379
    logging: *default-logging
  redisinsight: #Redis Client
    image: redislabs/redisinsight:${REDIS_INSIGHT_TAG-latest}
    container_name: redisinsight
    restart: on-failure
    volumes:
      - /var/volumes/redisinsight:/db
    ports:
      - 8001:8001
    logging: *default-logging
    links: 
      - redis
  rabbitmq:
      image: rabbitmq:${RABBITMQ_TAG-latest}
      container_name: rabbitmq
      ports:
          - 15672:15672
          - 5672:5672
          - 15693:15692
      volumes:
          - /var/volumes/rabbitmq:/var/lib/rabbitmq
      env_file:
        - .rabbitmq.env
      logging: *default-logging
  prometheus:
      image: prom/prometheus:${PROMETHEUS_TAG-latest}
      container_name: prometheus
      ports:
          - 9090:9090
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
      logging: *default-logging
  grafana:
      image: grafana/grafana:${GRAFANA_TAG-latest}
      container_name: grafana
      ports:
          - 3000:3000
      logging: *default-logging      
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./elasticsearch
    volumes:
      - /var/volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  k6:
      image: grafana/k6:${K6_TAG-latest}
      container_name: k6
      logging: *default-logging         
  localstack:
    image: localstack/localstack:${LOCALSTACK_TAG-latest}
    container_name: localstack
    ports:
      - 127.0.0.1:4510-4559:4510-4559  # external service port range
      - 127.0.0.1:4566:4566            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/var/volumes}/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    env_file: 
      - .localstack.env
    volumes:
      - "${TMPDIR:-/var/volumes}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  nginx:
      container_name: nginx
      build:
          context: ./nginx
      ports:
          - 80:80
          - 443:443
networks:    
  default: 
    name: services
    driver: bridge
